{% set version = "3.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tcpl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tcpl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tcpl/tcpl_{{ version }}.tar.gz
  sha256: 56a35a7f79afba20b237310f7fe9a412ba6d5111b1daa2cd55150d7b030be08c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-rcolorbrewer
    - r-rmariadb
    - r-ctxr >=1.1.0
    - r-data.table >=1.15.0
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-gt
    - r-numderiv
    - r-plotly
    - r-rlang
    - r-sqldf
    - r-stringr
    - r-tcplfit2
    - r-tidyr
    - r-viridis
  run:
    - r-base
    - r-dbi
    - r-rcolorbrewer
    - r-rmariadb
    - r-ctxr >=1.1.0
    - r-data.table >=1.15.0
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-gt
    - r-numderiv
    - r-plotly
    - r-rlang
    - r-sqldf
    - r-stringr
    - r-tcplfit2
    - r-tidyr
    - r-viridis

test:
  commands:
    - $R -e "library('tcpl')"           # [not win]
    - "\"%R%\" -e \"library('tcpl')\""  # [win]

about:
  home: https://github.com/USEPA/CompTox-ToxCast-tcpl
  license: MIT
  summary: A set of tools for processing and modeling high-throughput and high-content chemical screening data. The package was developed for the the chemical screening data generated by the US EPA ToxCast program, but can be used for diverse chemical screening efforts.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfakaehler
