{% set version = "3.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tcpl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tcpl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tcpl/tcpl_{{ version }}.tar.gz
  sha256: ebf400bfb8a0711407e61f0f5552dda52069e8216aa4075171a225e267926568

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-rcolorbrewer
    - r-rmariadb
    - r-data.table >=1.9.4
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-numderiv
    - r-plotly
    - r-sqldf
    - r-stringr
    - r-tcplfit2
    - r-tidyr
  run:
    - r-base
    - r-dbi
    - r-rcolorbrewer
    - r-rmariadb
    - r-data.table >=1.9.4
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-numderiv
    - r-plotly
    - r-sqldf
    - r-stringr
    - r-tcplfit2
    - r-tidyr

test:
  commands:
    - $R -e "library('tcpl')"           # [not win]
    - "\"%R%\" -e \"library('tcpl')\""  # [win]

about:
  home: https://github.com/USEPA/CompTox-ToxCast-tcpl
  license: MIT
  summary: A set of tools for processing and modeling high-throughput and high-content chemical screening data. The package was developed for the the chemical screening data generated by the US EPA ToxCast program, but can be used for diverse chemical screening efforts.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfakaehler

# Package: tcpl
# Title: ToxCast Data Analysis Pipeline
# Version: 2.0.2
# Authors@R: c( person("Richard S", "Judson",role = c("cre","ths"), email = "Judson.Richard@epa.gov"), person("Dayne L", "Filer", role = "aut",email = "dayne.filer@gmail.com"), person("Jason","Brown",role = "ctb", email = "brown.jason@epa.gov"), person("Todd", "Zurlinden", role="ctb", email="zurlinden.todd@epa.gov"), person("Parth", "Kothiya", role = "ctb"), person("Woodrow R", "Setzer", role = "ctb"), person("Matthew T", "Martin", role = c("ctb", "ths")), person("Katie", "Paul Friedman", role=c("ctb"), email = "paul-friedman.katie@epa.gov") )
# Description: A set of tools for processing and modeling high-throughput and high-content chemical screening data. The package was developed for the the chemical screening data generated by the US EPA ToxCast program, but can be used for diverse chemical screening efforts.
# URL: https://github.com/USEPA/CompTox-ToxCast-tcpl
# Depends: R (>= 3.2.0)
# Imports: data.table (>= 1.9.4), DBI, RMySQL, numDeriv, RColorBrewer, utils, stats, methods, graphics, grDevices, sqldf
# Suggests: roxygen2, knitr, prettydoc, rmarkdown, htmlTable
# License: GPL-2
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-07-26 13:41:17 UTC; jbrown20
# Author: Richard S Judson [cre, ths], Dayne L Filer [aut], Jason Brown [ctb], Todd Zurlinden [ctb], Parth Kothiya [ctb], Woodrow R Setzer [ctb], Matthew T Martin [ctb, ths], Katie Paul Friedman [ctb]
# Maintainer: Richard S Judson <Judson.Richard@epa.gov>
# Repository: CRAN
# Date/Publication: 2019-07-26 14:50:02 UTC
